# Generated by Django 3.1.4 on 2021-01-02 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0002_auto_20201228_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
