# Generated by Django 3.1.4 on 2021-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0003_auto_20210105_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='contestantId',
        ),
        migrations.AddField(
            model_name='contestant',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
