# Generated by Django 3.1.4 on 2021-01-05 09:47

import Election.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0004_auto_20210105_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='id',
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestantId',
            field=models.IntegerField(default=Election.models.generator, primary_key=True, serialize=False),
        ),
    ]
