# Generated by Django 3.1.4 on 2021-01-05 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0005_auto_20210105_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
