# Generated by Django 3.1.4 on 2021-01-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0007_auto_20210120_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='electionImage',
            field=models.ImageField(blank=True, upload_to='Election_Banners'),
        ),
    ]
