# Generated by Django 3.1.4 on 2021-01-01 09:25

import School.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electorateName', models.CharField(max_length=200, unique=True)),
                ('electorateEmail', models.EmailField(max_length=255, unique=True)),
                ('electorateId', models.IntegerField(default=School.models.generator, unique=True)),
                ('electorateApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
