# Generated by Django 3.1.4 on 2021-01-25 09:35

import Voters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not_Defined', 'Not_Defined')], default='1', max_length=12)),
                ('email', models.EmailField(default='@', max_length=254)),
                ('idNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('voterId', models.IntegerField(default=Voters.models.generator)),
                ('fatherName', models.CharField(max_length=40)),
                ('motherName', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('voted', models.BooleanField(default=False)),
                ('id', models.IntegerField(default=models.IntegerField(primary_key=True, serialize=False))),
                ('qualifiedElection', models.ManyToManyField(to='Election.Election')),
            ],
        ),
    ]
