# Generated by Django 3.1.4 on 2021-01-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('Voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='qualifiedElection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='School.electorate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='idNumber',
            field=models.IntegerField(),
        ),
    ]
