# Generated by Django 3.1.4 on 2021-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
        ('Voters', '0002_auto_20210102_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='qualifiedElection',
        ),
        migrations.AddField(
            model_name='voter',
            name='qualifiedElection',
            field=models.ManyToManyField(to='School.Electorate'),
        ),
    ]
