# Generated by Django 3.1.4 on 2021-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0002_auto_20201228_1922'),
        ('Voters', '0003_auto_20210102_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='qualifiedElection',
            field=models.ManyToManyField(to='Election.Election'),
        ),
    ]
