# Generated by Django 3.1.4 on 2021-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0004_auto_20210102_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='idNumber',
            field=models.IntegerField(max_length=13),
        ),
    ]
