# Generated by Django 3.1.4 on 2021-01-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0004_auto_20210104_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
