# Generated by Django 3.1.4 on 2021-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0005_auto_20210104_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Femaile', 'Female'), ('Not_Defined', 'Not_Defined')], default='1', max_length=12),
        ),
    ]
