# Generated by Django 3.1.4 on 2021-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0006_auto_20210116_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not_Defined', 'Not_Defined')], default='1', max_length=12),
        ),
    ]
