# Generated by Django 3.1.4 on 2021-01-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0007_auto_20210119_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(default='@', max_length=254),
            preserve_default=False,
        ),
    ]
