# Generated by Django 3.1.4 on 2021-01-19 16:53

import Voters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0008_voter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='idNumber',
            field=models.IntegerField(default=Voters.models.generator, primary_key=True, serialize=False),
        ),
    ]
