# Generated by Django 3.1.4 on 2021-01-19 19:25

import Voters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voters', '0009_auto_20210119_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voterId',
            field=models.IntegerField(default=Voters.models.generator),
        ),
        migrations.AlterField(
            model_name='voter',
            name='idNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
